name: big_data_engineering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - numba
  - pandas
  - pip
  - requests
  - scikit-learn>=1.4.0
  - seaborn
  - tqdm
  - pytest
  - pip:
    - jupyter
    - matplotlib
    - networkx
    - opencv-python
    - plotly
    - scipy>=1.8.0
    - umap-learn
